project:
  type: website
  output-dir: _site

filters:
  - _extensions/timestamp/timestamp.lua

website:
  title: ""
  description: "Documentation on experiments run on G3/G4 LED arena setups in the Reiser Lab at HHMI Janelia Research Campus."
  page-footer:
    center: "Page generated on {{< meta buildtime >}}"
  repo-url: https://github.com/leburnett/reiser-documentation
  favicon: /assets/favicon/favicon.ico

  navbar:
    background: dark
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Freely-walking"
        href: Freely-walking/index.qmd
      - text: "Electrophysiology"
        href: Ephys/index.qmd
      - text: "Tethered flight"
        href: Tethered/index.qmd
      - text: "Resources"
        href: resources.qmd
    right:
      - icon: github
        href: https://github.com/leburnett?tab=repositories

  sidebar:
    - title: "Freely-walking"
      collapse-level: 1
      contents:
        - Freely-walking/index.qmd
        - Freely-walking/freely_walking_quickstart.qmd
        - Freely-walking/freely-walking-rig-specs.qmd
        - section: "Protocols"
          contents:
            - Freely-walking/freely_walking_protocols_index.qmd
            - Freely-walking/freely_walking_logging_system.qmd
        - section: "Patterns"
          contents:
            - Freely-walking/freely_walking_patterns_index.qmd
        - section: "Analysis"
          contents:
            - Freely-walking/freely_walking_analysis.qmd
            - Freely-walking/freely-walking-analysis-new-protocol.qmd
        - section: "Reference"
          contents:
            - Freely-walking/freely_walking_data.qmd
            - Freely-walking/freely_walking_visualisation.qmd
            - Freely-walking/freely_walking_observations.qmd
        - Freely-walking/freely_walking_troubleshooting.qmd

    - title: "Electrophysiology"
      collapse-level: 1
      contents:
        - Ephys/index.qmd
        - Ephys/ephys_rig_specs.qmd
        - section: "Nested RF Protocol"
          contents:
            - Ephys/ephys_nested_rf.qmd
            - Ephys/ephys_nested_rf_getting-started.qmd
            - Ephys/ephys_nested_rf_concepts.qmd
            - section: "Protocol Descriptions"
              contents:
                - Ephys/ephys_nested_rf_protocol1.qmd
                - Ephys/ephys_nested_rf_protocol2.qmd
                - Ephys/ephys_nested_rf_version_history.qmd
            - section: "How-To Guides"
              contents:
                - Ephys/ephys_nested_rf_how-to-make.qmd
                - Ephys/ephys_nested_rf_how-to-run.qmd
                - Ephys/ephys_nested_rf_adapting-protocols.qmd
            - section: "Analysis"
              contents:
                - Ephys/ephys_nested_rf_how-to-analyse-p1.qmd
                - Ephys/ephys_nested_rf_how-to-analyse-p2.qmd
                - section: "Analysis Deep Dives"
                  contents:
                    - Ephys/ephys_nested_rf_bar-sweep-analysis.qmd
                    - Ephys/ephys_nested_rf_flash-analysis.qmd
                    - Ephys/ephys_nested_rf_bar-flash-analysis.qmd
                - Ephys/ephys_nested_rf_interpreting-results.qmd
            - section: "Reference"
              contents:
                - Ephys/ephys_nested_rf_code-architecture.qmd
                - Ephys/ephys_nested_rf_data_structure.qmd
                - Ephys/ephys_nested_rf_exp_log.qmd
            - Ephys/ephys_nested_rf_troubleshooting.qmd
        - section: "DS Probe Protocol"
          contents:
            - Ephys/ephys_ds_probe_protocol.qmd

    - title: "Tethered flight"
      collapse-level: 1
      contents:
        - Tethered/index.qmd

  page-navigation: true

format:
  html:
    theme:
      light: [yeti, theme-light.scss]
      dark: [yeti, theme-dark.scss]
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap

  pdf:
    documentclass: scrartcl
    toc: true
    number-sections: true
    colorlinks: true
